name: Deploy to Remote Server

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy code via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 47.236.248.233
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /var/www/html/
            git pull origin main
            sudo systemctl restart apache2

