name: Deploy to Remote Server

on:
  push:
    branches:
      - master  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: laxman-chaudhary/cicd  # Full repository path
          ref: master  # Branch name

      - name: Deploy code via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 47.236.248.233
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /var/www/html/  # Update this path if needed
            git pull origin master
            sudo systemctl restart apache2
