name: Deploy to Remote Server

on:
  push:
    branches:
      - master  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: laxman-chaudhary/cicd  # Your GitHub repository path
          ref: main  # Branch name

      - name: Deploy code via SSH
        uses: appleboy/ssh-action@v2
        with:
          host: 47.236.248.233  # Replace with your server's IP
          username: root  # Replace with your username
          password: Laxman007*  # SSH password
          script: |
            cd /var/www/html/cicd  # Update this path if needed
            git pull origin main
            # Additional deployment steps as needed
            sudo systemctl restart apache2  # Example: restart Apache service
