name: Deploy to Remote Server

on:
  push:
    branches:
      - master  # Change this to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Deploy code
      run: |
        sshpass -p "Laxman007*" scp -o StrictHostKeyChecking=no -r ./ root@47.236.248.233:/var/www/html/
        sshpass -p "Laxman007*" ssh -o StrictHostKeyChecking=no root@47.236.248.233 'service apache2 restart'
      env:
        SSHPASS: Laxman007*
